# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs

fastlane_version "2.25.0"

default_platform :ios

platform :ios do

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(
      type: "appstore",
      git_url: "https://github.com/sakshi108/certificates.git"
    ) # more information: https://codesigning.guide   
    gym(scheme: "AwesomeProject") # Build your app - more options available
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    pilot
  end

end
